---
format_version: 10
common:
  deploy_tasks: &deploy_tasks
    - exec:
        command: bash
        arguments:
         - -c
         - echo "Deployment to ${ENV_NAME} environment"

pipelines:
  node_micro:
    group: microservices
    materials:
      gitrepo:
        git: https://github.com/Gatis-Rozenbergs/ci_course.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments: 
                    - -c
                    - echo "Building application"
      - deploy-dev: 
          environment_variables:
            ENV_NAME: dev
          jobs:
            build: 
              tasks: *deploy_tasks
      - test-dev: 
          jobs:
            build: 
              tasks:
               - exec: 
                   command: bash
                   arguments: 
                   - -c
                   - echo "Testing on DEV"
      - deploy-int:
          environment_variables:
            ENV_NAME: int
          jobs:
            build: 
              tasks: *deploy_tasks
      - test-int: 
          jobs:
            build: 
              tasks:
               - exec: 
                   command: bash
                   arguments: 
                   - -c
                   - echo "Testing on INT"
      - deploy-prd:
        environment_variables:
            ENV_NAME: prod
          jobs:
            build: 
              tasks: *deploy_tasks
      - test-prd: 
          jobs:
            build: 
              tasks:
               - exec: 
                   command: bash
                   arguments: 
                   - -c
                   - echo "Testing on PRD"